server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10

spring:
  application:
    name: fever-marketplace

  datasource:
    url: jdbc:postgresql://localhost:5432/fever_marketplace
    username: ${DB_USER:fever}
    password: ${DB_PASSWORD:feverpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      external-provider:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5

  retry:
    instances:
      external-provider:
        max-attempts: 3
        wait-duration: 2s
        exponential-backoff-multiplier: 2

  timelimiter:
    instances:
      external-provider:
        timeout-duration: 10s

# Custom Configuration
fever:
  sync:
    interval: 30000 # 30 seconds
    enabled: true

  cache:
    bucket:
      ttl-hours: 6
      max-buckets-per-query: 24
      key-prefix: "fever:events:month:"
      current-month-ttl-hours: 2
      long-term-ttl-hours: 168
      enable-tiered-ttl: true
      async-invalidation: true

logging:
  level:
    com.fever.marketplace: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
