server:
  port: 8080

spring:
  application:
    name: fever-marketplace

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: ${DB_USER:fever}
    password: ${DB_PASSWORD:feverpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      external-provider:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

  retry:
    instances:
      external-provider:
        max-attempts: 3
        wait-duration: 2s

  timelimiter:
    instances:
      external-provider:
        timeout-duration: 10s

# Custom Configuration
fever:
  sync:
    interval: 3000 # 5 minutes
    enabled: true

  cache:
    bucket:
      ttl-hours: 6
      max-buckets-per-query: 24  # Monthly buckets, max 2 years
      key-prefix: "fever:events:month:"
      current-month-ttl-hours: 2  # Shorter TTL for current month
      enable-tiered-ttl: true

logging:
  level:
    com.fever.marketplace: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
